site_name: Daybook

theme:
  name: material
  palette: 
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
  - scheme: slate 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCwebj3UxpFP1hCgje16QxiQ
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/israteneda/
    - icon: fontawesome/brands/github
      link: https://github.com/israteneda